trigger:
- feature/azure

pool:
  name: 'Default'
  demands:
   - agent.name -equals self-hosted-windows
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'monsvt19/azurenodejs'
  # azureSubscription: '<your-subscription-name>'
  # resourceGroup: '<your-resource-group-name>'
  # aksClusterName: '<your-aks-cluster-name>'
  # dockerfilePath: './Dockerfile'
  # tag: '$(Build.BuildId)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm ci
    npm run build --if-present
    npm run test --if-present
  displayName: 'npm install, build and test'

- task: Docker@2
  inputs:
    containerRegistry: dockerhub
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    dockerfile: './Dockerfile'
    tags: |
      latest
  displayName: 'Build and push Docker image'